# Generated by Django 3.0.1 on 2020-07-21 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousecleaningReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRVC_START_DATE', models.DateField()),
                ('RESVE_LOCATION', models.CharField(max_length=300, null=True)),
                ('HAVE_PET', models.BooleanField(null=True)),
                ('HS_RESERVATION_REGIST_DATETIME', models.DateTimeField(auto_now_add=True)),
                ('HS_RESERVATION_UPDATE_DATETIME', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'HOUSECLEANING_RESERVATION',
            },
        ),
        migrations.CreateModel(
            name='ReserveCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RESVE_CYCLE', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'RESERVE_CYCLE',
            },
        ),
        migrations.CreateModel(
            name='ServiceDayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRVC_DAY_OF_WEEK', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'SERVICE_DAY_OF_WEEK',
            },
        ),
        migrations.CreateModel(
            name='ServiceDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRVC_DURATION', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SERVICE_DURATION',
            },
        ),
        migrations.CreateModel(
            name='ServiceStartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRVC_START_TIME', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SERVICE_START_TIME',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'STATUS',
            },
        ),
        migrations.CreateModel(
            name='ServiceDurationServiceStartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRVC_DURATION', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.ServiceDuration')),
                ('SRVC_START_TIME', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.ServiceStartTime')),
            ],
            options={
                'db_table': 'SERVICE_DURATION_SERVICE_START_TIME',
            },
        ),
        migrations.CreateModel(
            name='HousecleaningReservationServiceDayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HS_RESERVATION', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.HousecleaningReservation')),
                ('SRVC_DAY_OF_WEEK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.ServiceDayOfWeek')),
            ],
            options={
                'db_table': 'HOUSECLEANING_RESERVATION_SERVICE_DAY_OF_WEEK',
            },
        ),
        migrations.AddField(
            model_name='housecleaningreservation',
            name='RESVE_CYCLE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.ReserveCycle'),
        ),
        migrations.AddField(
            model_name='housecleaningreservation',
            name='SRVC_DAY_OF_WEEK_HC_RESERVATION',
            field=models.ManyToManyField(through='housecleaning.HousecleaningReservationServiceDayOfWeek', to='housecleaning.ServiceDayOfWeek'),
        ),
        migrations.AddField(
            model_name='housecleaningreservation',
            name='SRVC_DURATION',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.ServiceDuration'),
        ),
        migrations.AddField(
            model_name='housecleaningreservation',
            name='SRVC_START_TIME',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.ServiceStartTime'),
        ),
        migrations.AddField(
            model_name='housecleaningreservation',
            name='STATUS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.Status'),
        ),
        migrations.AddField(
            model_name='housecleaningreservation',
            name='USER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
    ]
