# Generated by Django 3.0.7 on 2020-08-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousecleaningReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_start_date', models.DateField()),
                ('reserve_location', models.CharField(max_length=300, null=True)),
                ('have_pet', models.BooleanField(null=True)),
                ('regist_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'HOUSECLEANING_RESERVATION',
            },
        ),
        migrations.CreateModel(
            name='ReserveCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_cycle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'RESERVE_CYCLE',
            },
        ),
        migrations.CreateModel(
            name='ServiceDayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_day_of_week', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'SERVICE_DAY_OF_WEEK',
            },
        ),
        migrations.CreateModel(
            name='ServiceDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_duration', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SERVICE_DURATION',
            },
        ),
        migrations.CreateModel(
            name='ServiceStartingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SERVICE_STARTING_TIME',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'STATUS',
            },
        ),
        migrations.CreateModel(
            name='ServiceDuration_ServiceStartingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVICE_DURATION', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.ServiceDuration')),
                ('SERVICE_STARTING_TIME', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.ServiceStartingTime')),
            ],
            options={
                'db_table': 'SERVICE_DURATION_SERVICE_STATING_TIME',
            },
        ),
        migrations.CreateModel(
            name='HousecleaningReservation_ServiceDayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOUSECLEANING_RESERVATION', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.HousecleaningReservation')),
                ('SERVICE_DAY_OF_WEEK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.ServiceDayOfWeek')),
            ],
            options={
                'db_table': 'HOUSECLEANING_RESERVATION_SERVICE_DAY_OF_WEEK',
            },
        ),
        migrations.AddField(
            model_name='housecleaningreservation',
            name='RESERVE_CYCLE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.ReserveCycle'),
        ),
        migrations.AddField(
            model_name='housecleaningreservation',
            name='SERVICE_DAY_OF_WEEK_HOUSECLEANING_RESERVATION',
            field=models.ManyToManyField(through='housecleaning.HousecleaningReservation_ServiceDayOfWeek', to='housecleaning.ServiceDayOfWeek'),
        ),
        migrations.AddField(
            model_name='housecleaningreservation',
            name='SERVICE_DURATION',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.ServiceDuration'),
        ),
        migrations.AddField(
            model_name='housecleaningreservation',
            name='SERVICE_STARTING_TIME',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.ServiceStartingTime'),
        ),
        migrations.AddField(
            model_name='housecleaningreservation',
            name='STATUS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housecleaning.Status'),
        ),
        migrations.AddField(
            model_name='housecleaningreservation',
            name='USER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
    ]
