# Generated by Django 3.0.1 on 2020-07-21 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MV_CTGRY_NAME', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'MOVE_CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='MoveReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MV_RV_ADDRESS', models.CharField(max_length=250, null=True)),
                ('MV_RV_MOBILE_NUMBER', models.CharField(max_length=100, null=True)),
                ('MV_RV_REGIST_DATETIME', models.DateTimeField(auto_now_add=True)),
                ('MV_RV_UPDATE_DATETIME', models.DateTimeField(auto_now=True)),
                ('MV_CTGRY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move.MoveCategory')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'MOVE_RESERVATION',
            },
        ),
    ]
