# Generated by Django 3.0.1 on 2020-07-27 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'MOVE_CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='MoveReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, null=True)),
                ('mobile_number', models.CharField(max_length=100, null=True)),
                ('regist_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('MOVE_CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move.MoveCategory')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'MOVE_RESERVATION',
            },
        ),
    ]
