-- create database
-- create database WISOv2 character set utf8mb4 collate utf8mb4_general_ci;

-- delete database
-- DROP DATABASE IF EXISTS WISOv2;


-- Status table
INSERT INTO STATUS(STATUS) VALUES('예약완료');

INSERT INTO STATUS(STATUS) VALUES('예약취소');

INSERT INTO STATUS(STATUS) VALUES('결제완료');

INSERT INTO STATUS(STATUS) VALUES('결제취소');


-- ServiceDayOfWeeks table
INSERT INTO SERVICE_DAY_OF_WEEK(SRVC_DAY_OF_WEEK) VALUES('월');

INSERT INTO SERVICE_DAY_OF_WEEK(SRVC_DAY_OF_WEEK) VALUES('화');

INSERT INTO SERVICE_DAY_OF_WEEK(SRVC_DAY_OF_WEEK) VALUES('수');

INSERT INTO SERVICE_DAY_OF_WEEK(SRVC_DAY_OF_WEEK) VALUES('목');

INSERT INTO SERVICE_DAY_OF_WEEK(SRVC_DAY_OF_WEEK) VALUES('금');

INSERT INTO SERVICE_DAY_OF_WEEK(SRVC_DAY_OF_WEEK) VALUES('토');

INSERT INTO SERVICE_DAY_OF_WEEK(SRVC_DAY_OF_WEEK) VALUES('일');


-- ServiceStartingTimes table
INSERT INTO SERVICE_START_TIME(SRVC_START_TIME) VALUES('오전9시');

INSERT INTO SERVICE_START_TIME(SRVC_START_TIME) VALUES('오전10시');

INSERT INTO SERVICE_START_TIME(SRVC_START_TIME) VALUES('오후2시');


-- ServiceDurations table
INSERT INTO SERVICE_DURATION(SRVC_DURATION) VALUES('3시간');

INSERT INTO SERVICE_DURATION(SRVC_DURATION) VALUES('4시간');

INSERT INTO SERVICE_DURATION(SRVC_DURATION) VALUES('8시간');


-- ReserveCycles table
INSERT INTO RESERVE_CYCLE(RESVE_CYCLE) VALUES('1회');

INSERT INTO RESERVE_CYCLE(RESVE_CYCLE) VALUES('매주');

INSERT INTO RESERVE_CYCLE(RESVE_CYCLE) VALUES('2주');

INSERT INTO RESERVE_CYCLE(RESVE_CYCLE) VALUES('4주');


-- ServiceDurations_ServiceStartingTimes table
INSERT INTO SERVICE_DURATION_SERVICE_START_TIME(SRVC_DURATION_id, SRVC_START_TIME_id) VALUES('1','2');

INSERT INTO SERVICE_DURATION_SERVICE_START_TIME(SRVC_DURATION_id, SRVC_START_TIME_id) VALUES('1','3');

INSERT INTO SERVICE_DURATION_SERVICE_START_TIME(SRVC_DURATION_id, SRVC_START_TIME_id) VALUES('2','1');

INSERT INTO SERVICE_DURATION_SERVICE_START_TIME(SRVC_DURATION_id, SRVC_START_TIME_id) VALUES('2','2');

INSERT INTO SERVICE_DURATION_SERVICE_START_TIME(SRVC_DURATION_id, SRVC_START_TIME_id) VALUES('3','1');


-- MOVE_CATEGORY table
INSERT INTO MOVE_CATEGORY(MV_CTGRY_NAME) VALUES('가정이사');

INSERT INTO MOVE_CATEGORY(MV_CTGRY_NAME) VALUES('소형이사');

INSERT INTO MOVE_CATEGORY(MV_CTGRY_NAME) VALUES('사무실이사');