# Generated by Django 3.0.1 on 2020-07-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_token', models.CharField(max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('mobile_number', models.CharField(max_length=11, null=True, unique=True)),
                ('regist_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
