# Generated by Django 3.0.1 on 2020-07-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USR_KAKAO_ID', models.CharField(max_length=200, null=True, unique=True)),
                ('USR_NAME', models.CharField(max_length=15)),
                ('USR_EMAIL', models.CharField(max_length=200, unique=True)),
                ('USR_PASSWORD', models.CharField(max_length=300)),
                ('USR_MOBILE_NUMBER', models.CharField(max_length=11, null=True, unique=True)),
                ('USR_REGIST_DATETIME', models.DateTimeField(auto_now_add=True)),
                ('USR_UPDATE_DATETIME', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
